name: SSHOP
main: SSHOP\SSHOP
version: 1.1.0
api: [3.0.0,2.0.0]
load: POSTWORLD
author: slm47888
depend: ["ZXDAKernel"]

commands:
  SSHOP:
    usage: /SSHOP help
    description: SSHOP so help
  S:
    usage: /S help
    description: SSHOP so help
