name: SSHOP
main: SSHOP\SSHOP
version: 1.2.5
api: [3.0.0,2.0.0]
load: POSTWORLD
author: slm47888
depend: ["ZXDAKernel"]

commands:
  sshop:
    usage: /sshop help
    description: SSHOP so help
  s:
    usage: /s help
    description: SSHOP so help
